#!/usr/bin/env python3
"""Add DVA (Developer Associate) questions to questions.json"""
import json
import os

QUESTIONS_PATH = os.path.join(os.path.dirname(__file__), '..', 'lib', 'questions.json')

DVA_QUESTIONS = [
    # Chapter 1: Lambda
    {"id": "dva01-1", "question": "AWS Lambda関数がAmazon S3バケットの新しいオブジェクトに応答して実行されるようにしたい。どのように設定すべきですか？", "choices": [{"label": "A", "text": "S3バケットにイベント通知を設定し、Lambda関数をトリガーとして指定する。"}, {"label": "B", "text": "Lambda関数にS3ポーリングを設定する。"}, {"label": "C", "text": "CloudWatch Eventsでスケジュールを設定してS3をチェックする。"}, {"label": "D", "text": "SQSキューを使用してS3イベントをキャプチャする。"}], "answer": ["A"], "multiSelect": False, "explanation": "S3バケットのイベント通知を設定し、Lambda関数を直接トリガーとして指定するのが最もシンプルで推奨される方法です。S3はプッシュモデルでLambdaを呼び出します。"},
    {"id": "dva01-2", "question": "Lambda関数の最大実行時間はどのくらいですか？", "choices": [{"label": "A", "text": "5分"}, {"label": "B", "text": "10分"}, {"label": "C", "text": "15分"}, {"label": "D", "text": "30分"}], "answer": ["C"], "multiSelect": False, "explanation": "AWS Lambda関数の最大実行時間（タイムアウト）は15分（900秒）です。これを超える処理にはStep FunctionsやECS/Fargateの利用を検討してください。"},
    {"id": "dva01-3", "question": "Lambda関数でコールドスタートを最小限に抑えるために使用できる機能はどれですか？", "choices": [{"label": "A", "text": "Lambda@Edge"}, {"label": "B", "text": "Provisioned Concurrency"}, {"label": "C", "text": "Reserved Concurrency"}, {"label": "D", "text": "Lambda Layers"}], "answer": ["B"], "multiSelect": False, "explanation": "Provisioned Concurrencyは、指定された数の実行環境を事前に初期化して維持するため、コールドスタートを排除できます。Reserved Concurrencyは同時実行数の上限を設定するもので、コールドスタートには影響しません。"},
    {"id": "dva01-4", "question": "Lambda関数のデプロイパッケージサイズの制限として正しいものはどれですか？", "choices": [{"label": "A", "text": "直接アップロード: 50MB、S3経由: 250MB（解凍後）"}, {"label": "B", "text": "直接アップロード: 100MB、S3経由: 500MB（解凍後）"}, {"label": "C", "text": "直接アップロード: 250MB、S3経由: 500MB（解凍後）"}, {"label": "D", "text": "直接アップロード: 50MB、S3経由: 500MB（解凍後）"}], "answer": ["A"], "multiSelect": False, "explanation": "Lambda関数のデプロイパッケージは直接アップロードで50MB、S3経由では解凍後250MBが上限です。コンテナイメージの場合は10GBまでサポートされます。"},
    {"id": "dva01-5", "question": "Lambda関数のバージョンとエイリアスについて正しい説明はどれですか？", "choices": [{"label": "A", "text": "エイリアスは不変（immutable）であり、一度作成すると変更できない。"}, {"label": "B", "text": "バージョンは可変（mutable）であり、コードを更新できる。"}, {"label": "C", "text": "エイリアスはバージョンを指すポインタであり、トラフィック分割に使用できる。"}, {"label": "D", "text": "$LATESTバージョンは不変である。"}], "answer": ["C"], "multiSelect": False, "explanation": "エイリアスはLambdaバージョンへのポインタで、2つのバージョン間でトラフィックを分割できます（加重エイリアス）。バージョンは不変で、$LATESTのみが可変です。"},
    # Chapter 2: DynamoDB
    {"id": "dva02-1", "question": "DynamoDBテーブルでホットパーティションの問題が発生しています。最も適切な解決策はどれですか？", "choices": [{"label": "A", "text": "プロビジョニングされたキャパシティを増やす。"}, {"label": "B", "text": "パーティションキーにランダムなサフィックスを追加してデータを分散させる。"}, {"label": "C", "text": "テーブルをオンデマンドモードに切り替える。"}, {"label": "D", "text": "グローバルセカンダリインデックスを追加する。"}], "answer": ["B"], "multiSelect": False, "explanation": "ホットパーティションはアクセスが特定のパーティションに集中することで発生します。パーティションキーにランダムなサフィックスを追加することで、データとリクエストを均等に分散できます。"},
    {"id": "dva02-2", "question": "DynamoDBで項目の条件付き書き込みを行いたい場合、どの機能を使用しますか？", "choices": [{"label": "A", "text": "BatchWriteItem"}, {"label": "B", "text": "Conditional Expressions（条件式）"}, {"label": "C", "text": "DynamoDB Streams"}, {"label": "D", "text": "Transaction API"}], "answer": ["B"], "multiSelect": False, "explanation": "Conditional Expressionsを使用すると、特定の条件が満たされた場合にのみ書き込みを実行できます。例えば、属性が存在しない場合にのみ項目を作成するなどが可能です。"},
    {"id": "dva02-3", "question": "DynamoDBでリアルタイムにテーブルの変更をキャプチャし、Lambda関数で処理したい場合、どの機能を使用すべきですか？", "choices": [{"label": "A", "text": "DynamoDB Accelerator (DAX)"}, {"label": "B", "text": "DynamoDB Global Tables"}, {"label": "C", "text": "DynamoDB Streams"}, {"label": "D", "text": "DynamoDB On-Demand Backup"}], "answer": ["C"], "multiSelect": False, "explanation": "DynamoDB Streamsはテーブルの項目レベルの変更をキャプチャし、変更が発生した順序で時系列のストリームとして提供します。Lambda関数をトリガーとして使用できます。"},
    {"id": "dva02-4", "question": "DynamoDBテーブルの読み取りキャパシティユニット（RCU）について、1RCUで処理できる読み取りはどれですか？", "choices": [{"label": "A", "text": "最大4KBの項目に対して、1秒あたり1回の強い整合性のある読み取り"}, {"label": "B", "text": "最大1KBの項目に対して、1秒あたり1回の強い整合性のある読み取り"}, {"label": "C", "text": "最大4KBの項目に対して、1秒あたり2回の強い整合性のある読み取り"}, {"label": "D", "text": "最大4KBの項目に対して、1秒あたり1回の結果整合性のある読み取り"}], "answer": ["A"], "multiSelect": False, "explanation": "1RCUは最大4KBの項目に対して、1秒あたり1回の強い整合性のある読み取りまたは2回の結果整合性のある読み取りを提供します。"},
    {"id": "dva02-5", "question": "DynamoDBのグローバルセカンダリインデックス（GSI）とローカルセカンダリインデックス（LSI）の違いについて正しいものはどれですか？", "choices": [{"label": "A", "text": "LSIはテーブル作成後に追加できるが、GSIはできない。"}, {"label": "B", "text": "GSIはテーブル作成後に追加できるが、LSIはテーブル作成時のみ定義できる。"}, {"label": "C", "text": "GSIとLSIの両方がテーブルと同じパーティションキーを使用する。"}, {"label": "D", "text": "LSIは異なるパーティションキーを定義できる。"}], "answer": ["B"], "multiSelect": False, "explanation": "GSIはテーブル作成後にいつでも追加・削除でき、異なるパーティションキーとソートキーを持てます。LSIはテーブル作成時のみ定義可能で、テーブルと同じパーティションキーを使用しますが異なるソートキーを持てます。"},
    # Chapter 3: API Gateway
    {"id": "dva03-1", "question": "API GatewayでLambda関数と統合する場合、Lambda プロキシ統合の利点はどれですか？", "choices": [{"label": "A", "text": "マッピングテンプレートを使用してリクエストとレスポンスを変換できる。"}, {"label": "B", "text": "Lambda関数がHTTPリクエストの完全な詳細を受け取り、HTTPレスポンスを直接返せる。"}, {"label": "C", "text": "API Gatewayがリクエストのバリデーションを自動的に行う。"}, {"label": "D", "text": "キャッシュが自動的に有効になる。"}], "answer": ["B"], "multiSelect": False, "explanation": "Lambda プロキシ統合では、API Gatewayがリクエスト全体をLambda関数に渡し、Lambda関数が直接HTTPレスポンス（ステータスコード、ヘッダー、ボディ）を返します。マッピングテンプレートは不要です。"},
    {"id": "dva03-2", "question": "API Gatewayのステージ変数の用途として正しいものはどれですか？", "choices": [{"label": "A", "text": "APIのレート制限を設定する。"}, {"label": "B", "text": "異なる環境（dev/staging/prod）で異なるバックエンドを指定する。"}, {"label": "C", "text": "APIのCORS設定を管理する。"}, {"label": "D", "text": "APIのキャッシュサイズを設定する。"}], "answer": ["B"], "multiSelect": False, "explanation": "ステージ変数は環境ごとの設定値として使用でき、異なるLambdaエイリアスやバックエンドURLを環境ごとに切り替えることができます。"},
    {"id": "dva03-3", "question": "API Gatewayでリクエストのスロットリングエラーが発生した場合、クライアントに返されるHTTPステータスコードはどれですか？", "choices": [{"label": "A", "text": "400 Bad Request"}, {"label": "B", "text": "403 Forbidden"}, {"label": "C", "text": "429 Too Many Requests"}, {"label": "D", "text": "503 Service Unavailable"}], "answer": ["C"], "multiSelect": False, "explanation": "API Gatewayでリクエストレート制限を超えた場合、429 Too Many Requestsが返されます。デフォルトのスロットリング制限はアカウントレベルで10,000リクエスト/秒です。"},
    # Chapter 4: SQS
    {"id": "dva04-1", "question": "Amazon SQSの可視性タイムアウトについて正しい説明はどれですか？", "choices": [{"label": "A", "text": "メッセージがキューに保持される最大時間を定義する。"}, {"label": "B", "text": "メッセージが受信された後、他のコンシューマーから見えなくなる時間を定義する。"}, {"label": "C", "text": "メッセージの暗号化に使用される時間を定義する。"}, {"label": "D", "text": "ロングポーリングの待機時間を定義する。"}], "answer": ["B"], "multiSelect": False, "explanation": "可視性タイムアウトは、コンシューマーがメッセージを受信した後、そのメッセージが他のコンシューマーから見えなくなる期間です。デフォルトは30秒で、最大12時間まで設定できます。"},
    {"id": "dva04-2", "question": "SQSのFIFOキューとスタンダードキューの違いについて正しいものはどれですか？（2つ選択）", "choices": [{"label": "A", "text": "FIFOキューはメッセージの順序を保証する。"}, {"label": "B", "text": "スタンダードキューのスループットはFIFOキューより低い。"}, {"label": "C", "text": "FIFOキューは重複排除を提供する。"}, {"label": "D", "text": "FIFOキューのスループット制限はない。"}], "answer": ["A", "C"], "multiSelect": True, "explanation": "FIFOキューはメッセージの順序保証と重複排除（Exactly-Once処理）を提供します。ただし、スループットは300メッセージ/秒（バッチで3,000）に制限されます。スタンダードキューはほぼ無制限のスループットです。"},
    {"id": "dva04-3", "question": "SQSのデッドレターキュー（DLQ）の目的は何ですか？", "choices": [{"label": "A", "text": "暗号化されたメッセージを保存する。"}, {"label": "B", "text": "正常に処理できなかったメッセージを隔離して調査する。"}, {"label": "C", "text": "高優先度のメッセージを格納する。"}, {"label": "D", "text": "期限切れのメッセージをアーカイブする。"}], "answer": ["B"], "multiSelect": False, "explanation": "DLQは、maxReceiveCount回受信されても正常に処理（削除）されなかったメッセージを移動する先のキューです。これにより、問題のあるメッセージを隔離して調査できます。"},
    # Chapter 5: CodeDeploy/CodePipeline/CodeBuild
    {"id": "dva05-1", "question": "AWS CodeDeployでEC2インスタンスへのデプロイに使用されるファイルはどれですか？", "choices": [{"label": "A", "text": "buildspec.yml"}, {"label": "B", "text": "appspec.yml"}, {"label": "C", "text": "template.yaml"}, {"label": "D", "text": "taskdef.json"}], "answer": ["B"], "multiSelect": False, "explanation": "appspec.ymlはCodeDeployがデプロイの各フェーズで実行するアクションを定義するファイルです。buildspec.ymlはCodeBuild用、template.yamlはCloudFormation/SAM用です。"},
    {"id": "dva05-2", "question": "AWS CodePipelineでソースステージからビルドステージ、デプロイステージまでの自動化されたパイプラインを構築しています。ビルドステージで使用すべきサービスはどれですか？", "choices": [{"label": "A", "text": "AWS CodeCommit"}, {"label": "B", "text": "AWS CodeBuild"}, {"label": "C", "text": "AWS CodeDeploy"}, {"label": "D", "text": "AWS CloudFormation"}], "answer": ["B"], "multiSelect": False, "explanation": "AWS CodeBuildはフルマネージドのビルドサービスで、ソースコードのコンパイル、テスト実行、デプロイ可能なパッケージの生成を行います。CodeCommitはソース管理、CodeDeployはデプロイに使用します。"},
    {"id": "dva05-3", "question": "CodeDeployのBlue/Greenデプロイメントの利点として正しいものはどれですか？", "choices": [{"label": "A", "text": "デプロイ時にインスタンスが不要になる。"}, {"label": "B", "text": "問題発生時に元のバージョンに即座にロールバックできる。"}, {"label": "C", "text": "デプロイ中にダウンタイムが必ず発生する。"}, {"label": "D", "text": "In-placeデプロイメントより常にコストが低い。"}], "answer": ["B"], "multiSelect": False, "explanation": "Blue/Greenデプロイメントでは、新しいバージョン（Green）を別のインスタンスセットにデプロイし、トラフィックを切り替えます。問題があれば、元の環境（Blue）にトラフィックを戻すだけで即座にロールバックできます。"},
    # Chapter 6: X-Ray
    {"id": "dva06-1", "question": "AWS X-Rayでアプリケーションのパフォーマンス問題を特定するために使用される概念はどれですか？", "choices": [{"label": "A", "text": "セグメントとサブセグメント"}, {"label": "B", "text": "メトリクスとアラーム"}, {"label": "C", "text": "ログとフィルター"}, {"label": "D", "text": "トレイルとイベント"}], "answer": ["A"], "multiSelect": False, "explanation": "X-Rayはセグメント（サービスでの作業単位）とサブセグメント（AWS SDKコール、HTTPコール等の詳細）を使用してリクエストをトレースし、パフォーマンスボトルネックを特定します。"},
    {"id": "dva06-2", "question": "Lambda関数でX-Rayトレーシングを有効にするために必要な設定はどれですか？（2つ選択）", "choices": [{"label": "A", "text": "Lambda関数の設定でアクティブトレーシングを有効にする。"}, {"label": "B", "text": "Lambda関数にX-Rayデーモンをインストールする。"}, {"label": "C", "text": "Lambda関数の実行ロールにX-Rayの書き込み権限を付与する。"}, {"label": "D", "text": "Lambda関数のVPC設定でX-Rayエンドポイントを追加する。"}], "answer": ["A", "C"], "multiSelect": True, "explanation": "Lambda関数でX-Rayを使用するには、(1)関数設定でアクティブトレーシングを有効にし、(2)実行ロールにAWSXRayDaemonWriteAccessポリシーを追加します。X-RayデーモンはLambdaサービスに組み込まれています。"},
    # Chapter 7: Cognito
    {"id": "dva07-1", "question": "Amazon Cognito User PoolsとIdentity Poolsの違いについて正しいものはどれですか？", "choices": [{"label": "A", "text": "User Poolsは認証（Authentication）を提供し、Identity Poolsは認可（Authorization）でAWSリソースへのアクセスを提供する。"}, {"label": "B", "text": "Identity PoolsはユーザーのサインアップとサインインをUI管理する。"}, {"label": "C", "text": "User PoolsはAWSサービスへの一時的な認証情報を発行する。"}, {"label": "D", "text": "User PoolsとIdentity Poolsは同じ機能を提供する。"}], "answer": ["A"], "multiSelect": False, "explanation": "Cognito User Poolsはユーザーディレクトリで、認証（サインアップ/サインイン）とJWTトークンの発行を行います。Identity Poolsは認証されたユーザーにAWSサービスへの一時的な認証情報を提供します。"},
    {"id": "dva07-2", "question": "Cognito User Poolsでソーシャルログイン（Google、Facebook）を統合する場合に使用する機能はどれですか？", "choices": [{"label": "A", "text": "フェデレーション ID プロバイダー"}, {"label": "B", "text": "カスタム認証チャレンジ"}, {"label": "C", "text": "MFA設定"}, {"label": "D", "text": "ユーザープール属性"}], "answer": ["A"], "multiSelect": False, "explanation": "Cognito User Poolsのフェデレーション ID プロバイダー機能を使用して、Google、Facebook、Amazon、Apple等のソーシャルIDプロバイダーやSAML/OIDCプロバイダーとの統合が可能です。"},
    # Chapter 8: CloudFormation/SAM
    {"id": "dva08-1", "question": "AWS SAM（Serverless Application Model）テンプレートで必須のトランスフォーム宣言はどれですか？", "choices": [{"label": "A", "text": "Transform: AWS::Serverless-2016-10-31"}, {"label": "B", "text": "Transform: AWS::CloudFormation-2010-09-09"}, {"label": "C", "text": "Transform: AWS::Lambda-2015-03-31"}, {"label": "D", "text": "Transform: AWS::SAM-2023-01-01"}], "answer": ["A"], "multiSelect": False, "explanation": "SAMテンプレートにはTransform: AWS::Serverless-2016-10-31の宣言が必須です。これによりCloudFormationがSAM固有のリソースタイプ（AWS::Serverless::Function等）を認識できます。"},
    {"id": "dva08-2", "question": "CloudFormationテンプレートでスタック間でリソースを共有するために使用する機能はどれですか？", "choices": [{"label": "A", "text": "Parameters"}, {"label": "B", "text": "Mappings"}, {"label": "C", "text": "Outputs と Cross-stack references (Fn::ImportValue)"}, {"label": "D", "text": "Conditions"}], "answer": ["C"], "multiSelect": False, "explanation": "Outputsセクションでエクスポートした値を、他のスタックでFn::ImportValueを使って参照できます。これがCross-stack referenceです。"},
    # Chapter 9: Elastic Beanstalk
    {"id": "dva09-1", "question": "Elastic Beanstalkでデプロイ中のダウンタイムなしに新バージョンをデプロイし、失敗時に素早くロールバックしたい場合、最適なデプロイポリシーはどれですか？", "choices": [{"label": "A", "text": "All at once"}, {"label": "B", "text": "Rolling"}, {"label": "C", "text": "Rolling with additional batch"}, {"label": "D", "text": "Immutable"}], "answer": ["D"], "multiSelect": False, "explanation": "Immutableデプロイは新しいAuto Scaling Groupに新バージョンのインスタンスを起動するため、ダウンタイムがなく、失敗時は新しいインスタンスを削除するだけで素早くロールバックできます。"},
    {"id": "dva09-2", "question": "Elastic Beanstalk環境の設定をカスタマイズするために、.ebextensionsディレクトリに配置するファイルの拡張子はどれですか？", "choices": [{"label": "A", "text": ".json"}, {"label": "B", "text": ".yaml"}, {"label": "C", "text": ".config"}, {"label": "D", "text": ".yml"}], "answer": ["C"], "multiSelect": False, "explanation": ".ebextensionsディレクトリには.config拡張子のファイルを配置します。これらのファイルはYAMLまたはJSON形式で記述でき、環境のカスタマイズ（パッケージ、ファイル、コマンド等）を定義します。"},
    # Chapter 10: ECS/ECR
    {"id": "dva10-1", "question": "Amazon ECSでFargateランチタイプを使用する場合の利点はどれですか？", "choices": [{"label": "A", "text": "EC2インスタンスのプロビジョニングと管理が不要になる。"}, {"label": "B", "text": "GPUワークロードをサポートする。"}, {"label": "C", "text": "EC2ランチタイプよりも常にコストが低い。"}, {"label": "D", "text": "Dockerイメージが不要になる。"}], "answer": ["A"], "multiSelect": False, "explanation": "Fargateはサーバーレスコンテナ実行環境で、EC2インスタンスの管理が不要です。タスク定義でCPUとメモリを指定するだけで、インフラはAWSが管理します。"},
    {"id": "dva10-2", "question": "Amazon ECRにDockerイメージをプッシュする前に必要なコマンドはどれですか？", "choices": [{"label": "A", "text": "aws ecr get-login-password でログインする"}, {"label": "B", "text": "aws ecs register-task-definition を実行する"}, {"label": "C", "text": "aws s3 cp でイメージをアップロードする"}, {"label": "D", "text": "aws lambda update-function-code を実行する"}], "answer": ["A"], "multiSelect": False, "explanation": "ECRにイメージをプッシュする前に、aws ecr get-login-passwordコマンドで認証トークンを取得し、docker loginでECRレジストリに認証する必要があります。"},
    # Chapter 11: KMS/Encryption
    {"id": "dva11-1", "question": "AWS KMSのエンベロープ暗号化について正しい説明はどれですか？", "choices": [{"label": "A", "text": "データキーでデータを暗号化し、CMKでデータキーを暗号化する二層構造"}, {"label": "B", "text": "CMKで直接データを暗号化する単一層構造"}, {"label": "C", "text": "S3サーバーサイド暗号化専用の手法"}, {"label": "D", "text": "クライアントサイド暗号化でのみ使用される手法"}], "answer": ["A"], "multiSelect": False, "explanation": "エンベロープ暗号化では、GenerateDataKeyでデータキーを生成し、そのデータキーでデータを暗号化します。データキー自体はCMK（カスタマーマスターキー）で暗号化されます。大きなデータを効率的に暗号化できます。"},
    {"id": "dva11-2", "question": "S3バケットに暗号化されていないオブジェクトのアップロードを防止するにはどうすればよいですか？", "choices": [{"label": "A", "text": "バケットポリシーでx-amz-server-side-encryptionヘッダーがないPUTリクエストを拒否する。"}, {"label": "B", "text": "IAMポリシーでs3:PutObjectアクションを拒否する。"}, {"label": "C", "text": "S3バージョニングを有効にする。"}, {"label": "D", "text": "S3 Object Lockを有効にする。"}], "answer": ["A"], "multiSelect": False, "explanation": "バケットポリシーでConditionを使い、x-amz-server-side-encryptionヘッダーが含まれていないPUTリクエストを拒否するDenyステートメントを追加することで、暗号化されていないアップロードを防止できます。"},
    # Chapter 12: Step Functions
    {"id": "dva12-1", "question": "AWS Step Functionsのステートマシンでエラーハンドリングに使用される機能はどれですか？（2つ選択）", "choices": [{"label": "A", "text": "Catch"}, {"label": "B", "text": "Wait"}, {"label": "C", "text": "Retry"}, {"label": "D", "text": "Choice"}], "answer": ["A", "C"], "multiSelect": True, "explanation": "Step FunctionsではRetry（再試行）とCatch（エラーキャッチ）を使用してエラーハンドリングを行います。Retryは指数バックオフで再試行し、Catchはエラー時に代替パスへ遷移します。"},
    {"id": "dva12-2", "question": "Step FunctionsのStandard WorkflowとExpress Workflowの違いについて正しいものはどれですか？", "choices": [{"label": "A", "text": "Standard Workflowの最大実行時間は5分、Express Workflowは1年"}, {"label": "B", "text": "Express Workflowの最大実行時間は5分で、高スループットワークロード向け"}, {"label": "C", "text": "Standard WorkflowはExpress Workflowより常にコストが低い"}, {"label": "D", "text": "Express Workflowは実行履歴を1年間保持する"}], "answer": ["B"], "multiSelect": False, "explanation": "Express Workflowは最大5分の実行時間で、高スループット・短時間のワークロード向けです。Standard Workflowは最大1年の実行時間で、長時間の処理や可視性が必要な場合に適しています。"},
]

def main():
    with open(QUESTIONS_PATH, 'r', encoding='utf-8') as f:
        existing = json.load(f)
    
    existing_ids = {q['id'] for q in existing}
    new_questions = [q for q in DVA_QUESTIONS if q['id'] not in existing_ids]
    
    print(f"Existing questions: {len(existing)}")
    print(f"New DVA questions to add: {len(new_questions)}")
    
    existing.extend(new_questions)
    existing.sort(key=lambda q: q['id'])
    
    with open(QUESTIONS_PATH, 'w', encoding='utf-8') as f:
        json.dump(existing, f, ensure_ascii=False, indent=2)
    
    exams = {}
    for q in existing:
        exam = q['id'][:3]
        exams[exam] = exams.get(exam, 0) + 1
    
    print(f"\nTotal questions: {len(existing)}")
    for k, v in sorted(exams.items()):
        print(f"  {k.upper()}: {v}")

if __name__ == '__main__':
    main()
